### ISSUE TITLE
DarkMode - minor bug with font vs background colours

### ISSUE THREAD

**Issue by marshj1977** [bitclout/frontend#102]
As per my post (https://bitclout.com/posts/08495e91ffcea09c9f8ecb06e10c7c09e3e7df8c675e96d495915e16f9d61de9?messagesTab=all ).

Bug in display of some menus (e.g. reclout drop down):-

![darkmode_oversight](https://user-images.githubusercontent.com/83847905/121174653-0c0d3e00-c852-11eb-9769-f6e1555e003d.png)

I'm sure this is a really simple fix, but wanted to log it here so it would get seen :)

Cheers for all the hard work guys

**Comment by lazynina** [comment]
@marshj1977 I believe this is now resolved.  Is this still an issue in your mind? If not, I'd like to close this.

**Comment by marshj1977** [comment]
Hi @lazynina yes - looks like its resolved on the reclout option :)
