### ISSUE TITLE
Query the back-end to validate a public key

### ISSUE THREAD

**Issue by gpmarchi** [bitclout/frontend#121]
Hi,

I was wondering if there is an endpoint on bitclout's back-end that would tell if any given public key is valid.

I have been looking at the code for the front-end and I found some endpoints but I haven't figured out how to use them.

Like this one for instance:  https://bitclout.com/api/v0/get-single-profile

What I would like to do is pass on to some endpoint a bitclout user's public key and see if it is valid.

Could someone please help me figure this out?

**Comment by maebeam** [comment]
Could you expand on what you mean by valid? If you mean has a balance or a profile, then get single profile should return the information you need.

**Comment by gpmarchi** [comment]
Yes by valid I meant an existing public key, anyone can query and see that is registered on bitclout's nodes.

Actually I was wondering if there are any docs on the endpoints so one knows what sort of information is possible to get from the back-end.

**Comment by maebeam** [comment]
This user is working on some docs you might find helpful: https://github.com/bitclout/docs/pull/13/files?short_path=5790456#diff-5790456b4e2b89b2b1f4777f5e271bb31b8a53623d513cc299f9de7fd7b689c4

**Comment by gpmarchi** [comment]
This is awesome @maebeam thanks a lot.
