### ISSUE TITLE
New profile images not scaled for small notifications

### ISSUE THREAD

**Issue by tijno** [bitclout/frontend#131]
Small issue with update just repoyed @lazynina - can PR if needed but its tiny. 

![20210612-uelwlfBH](https://user-images.githubusercontent.com/69529928/121781588-5ae20d00-cb9d-11eb-8210-4211742e7710.png)

background image not scaled properly 

suggest css addition to `.notifications__avatar`

```
background-size: auto 100%;
```

So it looks correct like this:

![20210612-RIy7myM1](https://user-images.githubusercontent.com/69529928/121781616-8d8c0580-cb9d-11eb-8ca4-2d8a099b586c.png)

**Comment by lazynina** [comment]
resolved with #136
