### ISSUE TITLE
Easy "lists" feature for Bitclout

### ISSUE THREAD

**Issue by tijno** [bitclout/frontend#138]
Let me know if your interested in this feature and ill submit as a PR @maebeam @lazynina 

* New "Watching" feed tab
* Select box listing the "secondary" accounts, eg not the one you are logged in as right now
* Use it to view feeds from the other account, but reply, like, diamond with your main account
* This allows you to create simple twitter like Lists
* Selection is persisted through local storage

Its live on tijn.club but needs to tidying & commenting.

![20210612-mw42XPsF](https://user-images.githubusercontent.com/69529928/121789123-40268d00-cbcb-11eb-9466-4fbfa38cf2a3.gif)

Let me know

**Comment by ropolexi** [comment]
I got this error message
![Screenshot_2021-06-13_09-24-16](https://user-images.githubusercontent.com/83857790/121794852-52cfaf00-cc29-11eb-949d-698e6d184fbb.png)

**Comment by ropolexi** [comment]
I got this error message
![Screenshot_2021-06-13_09-27-46](https://user-images.githubusercontent.com/83857790/121794880-ab9f4780-cc29-11eb-9c0c-087ee287a231.png)

**Comment by tijno** [comment]
@ropolexi fixed.

note you have to be logged into multiple accounts in the dropdown top left hand menu.

![20210613-DFKwbv3t](https://user-images.githubusercontent.com/69529928/121798187-cf0fc580-cc1c-11eb-9246-f1ef133227d6.png)

When you are not logged in at all, or if you re only logged into 1 account it will now show custom message.

![20210613-sQzZ65Cr](https://user-images.githubusercontent.com/69529928/121798199-df27a500-cc1c-11eb-9303-c922674aa61d.png)

**Comment by tijno** [comment]
Im closing this and will resubmit as a CIPs
