### ISSUE TITLE
<Message is not decryptable on this device> 

### ISSUE THREAD

**Issue by AeonSw4n** [bitclout/frontend#145]
As the title says. Is this intentional or is it a bug?

![Screenshot from 2021-06-13 16-57-04](https://user-images.githubusercontent.com/29924594/121821681-7403c000-cc68-11eb-9a7f-1d355fab62f5.png)

**Comment by AdityaChaudhary0005** [comment]
Messages you send are private to your browser. I don't think it is a bug

**Comment by AeonSw4n** [comment]
Sending messages doesn't require browser information. Only reading does.

Imo this seems counterintuitive.  End-to-end messaging should relay solely on the keys.

**Comment by maebeam** [comment]
Unfortunately this is by design. When you send a message you encrypt it with the other user's public key so only they can read it.

**Comment by AeonSw4n** [comment]
It makes sense, my node sent this message using the `/api/v0/send-message-stateless` endpoint. But why wouldn't the recipient be able to decrypt it? The message is already associated with his public key. 

I can send you more screenshots if you want. Interestingly, some people can read these messages and some can't.

(@maebeam sorry for the tag)
