### ISSUE TITLE
Invalid Token on Messages(inbox) page

### ISSUE THREAD

**Issue by Cardoso-topdev** [bitclout/frontend#162]
<h3>I have an invalid token problem on the messages page. When this happens and how can I solve this problem?</h3>
<be />
<be />

![image](https://user-images.githubusercontent.com/75736745/121904976-46ae2500-ccef-11eb-8b3e-b9347b83ac5b.png)

**Comment by maebeam** [comment]
Your computer clock is likely incorrect. Make sure it's set to automatic and the correct date and time. Let me know if that doesn't help!
