### ISSUE TITLE
Proposed setup for proper title/meta and embed tags

### ISSUE THREAD

**Issue by tijno** [bitclout/frontend#185]
I have implemented post and user embed functionality on tijn.club- which i think you saw and liked @lazynina 

![20210617-8b3gokTg](https://user-images.githubusercontent.com/69529928/122442918-fa850e00-cf96-11eb-9db3-831ae8131864.gif)

![20210617-vEmH26PX](https://user-images.githubusercontent.com/69529928/122442932-fd7ffe80-cf96-11eb-946c-6789b8bfc4b4.gif)

The setup is as followed:

1) cloudflare worker for `/u/` and `/posts/` urls
2) worker checks cache for user profile / post data, if not in cache will request from api
3) worker rewrites opengraph, twitter card meta & title tags in index.html
4) outputs response to requester

This enables following benefits:

* Hugely improved SEO for posts & user profiles as key details are in the title now.
* Better embedding of posts on social media and discord, driving more new users to bitclout

As bitclout is for now the primary site people use, it would be great to move this functionality to bitclout.com

The worker script is super simple, and as you already use cloutflare it is a relatively easy step to implement i think.

Let me know if you are interested.

**Comment by maebeam** [comment]
Fantastic idea! I'd love to get this up and running

**Comment by tijno** [comment]
great @maebeam i will create a separate repo for the worker script and set it so it can auto deploy to cloudflare on commit with github action and will provide some setup instructions.

then you can just fork it and deploy to your own account. 

node operators can then do the same if they want.

If you can provide some traffic stats hitting post and user pages - i can also do estimate what the likely cost from cloudflare would be for this.

**Comment by maebeam** [comment]
Great work @tijno! Should we close this issue?

**Comment by tijno** [comment]
yep ill let you know when repo is ready

**Comment by tijno** [comment]
@maebeam PR added - it points to the repo with the worker code

**Comment by tijno** [comment]
Will this be added to the new frontend you are working on - it will help ￼￼people share the links and show relevant content

**Comment by AdityaChaudhary0005** [comment]
+1 to what @tijno just said above. It's a life saver while embedding posts on platforms like discord and it also improves the SEO

**Comment by maebeam** [comment]
I will reprioritize adding this to bitclout.com

**Comment by tijno** [comment]
great news @maebeam ill make some updates to the embed repo inlight of DeSo rebrand and add NFT support.

**Comment by tijno** [comment]
Updated & rebranded repo with cloudflare worker script here:
https://github.com/DeSoDev/EmbeDeSo

NFT support added.
Improved setup steps in readme.
Improved the twitter embed as well:

![20210928-wZPg0YtH](https://user-images.githubusercontent.com/69529928/135155800-d0791d85-b2b2-4bdf-9335-1a7c0696f9c3.png)
