### ISSUE TITLE
wrong value in this.globalVars.nanosPerUSDExchangeRate

### ISSUE THREAD

**Issue by electro89** [bitclout/frontend#205]
I get wrong value for this.globalVars.nanosPerUSDExchangeRate

**Comment by maebeam** [comment]
Can you provide some more information?

**Comment by electro89** [comment]
In the admin.component.ts I can not get coin price using 
console.log(this.globalVars.nanosToUSDNumber(res.PostsFound[i].ProfileEntryResponse.CoinPriceBitCloutNanos));

**Comment by maebeam** [comment]
I'll need to know a bit more information to help out. For example, the result of the console log and `ProfileEntryResponse` and /api/v0/get-exchange-rate
