### ISSUE TITLE
Can't transfer $CLOUT to anonymous wallets/Exchange

### ISSUE THREAD

**Issue by ShhubhamA** [bitclout/frontend#214]
Seems like after introduction of the feature of "showing who are we sending Clouts too " We are not able to send the Clout to Anonymous/Exchange wallets  and the error which is popping is :

"Error loading profiles: GetSingleProfile: could not find profile for username or public key: "

**Comment by BogdanDidenko** [comment]
> Seems like after introduction of the feature of "showing who are we sending Clouts too " We are not able to send the Clout to Anonymous/Exchange wallets and the error which is popping is :
> 
> "Error loading profiles: GetSingleProfile: could not find profile for username or public key: "

@lazynina look at this this is a critical issue

**Comment by AdityaChaudhary0005** [comment]
yes, i second what @ShhubhamA said!
This is frontend issue as @lazynina brought up the "show who are we sending clouts to" feature.

On a side note, phone number verification doesn't work (no starter CLOUT for new users) and neither any existing user can help them by sending CLOUT at the moment

**Comment by AdityaChaudhary0005** [comment]
UPDATE: they have already fixed it: https://github.com/bitclout/frontend/pull/213

@ShhubhamA you can close this issue now. The deployment of new frontend version will take time

**Comment by BogdanDidenko** [comment]
BitClout team, hire QAs, you have money
