### ISSUE TITLE
Run Frontend Local without Backend

### ISSUE THREAD

**Issue by harpreet9629** [bitclout/frontend#220]
Hi,

How i can run Frontend at local, without running backend? I run ng serve it open Frontend but I can't login and no data fetched.

**Comment by maebeam** [comment]
We don't currently support running a local frontend without a local backend.

**Comment by harpreet9629** [comment]
There is no command mentioned in docs for run backend. Should I have to run my node as well?

**Comment by maebeam** [comment]
These docs explain how to run a frontend and backend node: https://docs.bitclout.com/code/dev-setup

**Comment by harpreet9629** [comment]
i am following it, but i can't able to sign in or sign up

**Comment by harpreet9629** [comment]
I am trying in windows 10

**Comment by maebeam** [comment]
For further assistance I'd recommend joining the community Discord: http://discord.gg/bitclout
