### ISSUE TITLE
Not reloading feed

### ISSUE THREAD

**Issue by harpreet9629** [bitclout/frontend#221]
When I switch to another account it won't refresh/reload feed, I saw my previous account clouts. (I liked, reclouted, diamond) all show previous account details.

**Comment by AdityaChaudhary0005** [comment]
yeah, i have experienced this sometimes.
the only solution is to reload the page.

**Comment by harpreet9629** [comment]
But i can be fix as same when change name and page it reload feed also on switch account

**Comment by tijno** [comment]
If you know fix - best is to submit a PR with the fix. Its more likely to get fixed then.
