### ISSUE TITLE
Show Title, Meta on Bitclout

### ISSUE THREAD

**Issue by harpreet9629** [bitclout/frontend#222]
Hi Team,

Can you show Title, Meta of shared link on bitclout? I will try to make repo, @tijno can you do this please.

**Comment by tijno** [comment]
is it any different then the cloutembed pr i posted ?

**Comment by harpreet9629** [comment]
I think, its same as when we post any another site link on twitter and it show its meta content
Title, Image, Description

<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@user" />
<meta name="twitter:creator" content="@user" />
<meta property="og:url" content="URL_LINK" />
<meta property="og:title" content="A Twitter" />
<meta property="og:description" content="Some Description" />
<meta property="og:image" content="ImageURL" />

**Comment by tijno** [comment]
@maebeam @lazynina i see you merged the changes to the index.html file and closed https://github.com/bitclout/frontend/pull/204

But the worked side to fully enable proper embeds has not been added into your stack.

Do you need a different solution, or is it just a timing thing ?

**Comment by maebeam** [comment]
@harpreet9629 This has already been solved by @tijno in #204.

@tijno I have it tracked and will get it done sometime soon

**Comment by harpreet9629** [comment]
Its not @tijno worker, i m saying for embed every site url and show site meta data on BitClout Fronted, when someone post a link.

@tijno worker show only posted clout meta data, i m right?

**Comment by tijno** [comment]
ah @harpreet9629 you mean links posted on bitclout ? 

like a twitter link posted in a clout shows the twitter card ? 

because if you mean bitclout links posted for example on Discord then my PR solves that already

**Comment by harpreet9629** [comment]
ah @harpreet9629, you mean links posted on Bitclout?
Correct Pick

like a Twitter link posted in a clout shows the Twitter card? 
Yes
