### ISSUE TITLE
Approval required for every transaction 1 week after log in on Safari

### ISSUE THREAD

**Issue by this-is-simon** [bitclout/frontend#224]
We're having an issue on Safari desktop with approvalRequired on the React web app we're building:

Given that I'm using Safari
And I logged in 1 week ago with access level 4
When I attempt to buy a coin
Identity requires me to Approve Transaction
And it requires me to approve every single transaction following that
Despite the fact that the seed-hex-key in Cookies is now correctly updated to last another week (i.e. now to expire 2 weeks from when I originally logged in)

Deleting my local storage manually and re-logging in means I don't have to approve each transaction, at least for another week. Really we want users to be able to log into the web app once at access level 4 and only have to approve a transaction when absolutely necessary. I'm not sure if I'm missing something?

**Comment by tijno** [comment]
i have the same experience on bitclout.com where i have to sign a transaction ones a week.

ITP wipes non cookie data after 7 days for first party domains

see https://webkit.org/tracking-prevention/

7 day cap section:

> Therefore, ITP caps the expiry of all cookies created in JavaScript to 7 days and deletes all other script-writeable storage after 7 days of no user interaction with the website.

**Comment by this-is-simon** [comment]
> i have the same experience on bitclout.com where i have to sign a transaction ones a week.
> 
> ITP wipes non cookie data after 7 days for first party domains
> 
> see https://webkit.org/tracking-prevention/
> 
> 7 day cap section:
> 
> > Therefore, ITP caps the expiry of all cookies created in JavaScript to 7 days and deletes all other script-writeable storage after 7 days of no user interaction with the website.

Understood, the issue I'm reporting is that even when I approve a transaction after 1 week, every transaction following that _also_ requires approval.

**Comment by maebeam** [comment]
For future reference this issue was moved https://github.com/bitclout/identity/issues/49
