### ISSUE TITLE
Bookmark and Share Posts

### ISSUE THREAD

**Issue by Shubs21** [bitclout/frontend#270]
Implementing the 'Bookmark Post' and 'Share Post' functionality by having a 'Dropdown List' in place of the current 'Copy Link' Button. 

This has numerous benefits, some of them are mentioned👇🏻

1. Saves time as finding posts is a hassle for the average user. (Bookmarks)
2. Easy cross-platform sharing is free marketing and enhances user experience. (Share Post)
3. It'll be fun to peek into Balaji's Bookmarks :P (Project Idea?)

![image](https://user-images.githubusercontent.com/87209627/125203219-390ba100-e295-11eb-9c40-932ae3cb9d54.png)

**Comment by tijno** [comment]
@Shubs21 like it - but to implement this you would need to add a transaction i think so this becomes a large change. So best to log it as discussion https://github.com/bitclout/cips and get buying from community & 1 core dev.

**Comment by Shubs21** [comment]
> @Shubs21 like it - but to implement this you would need to add a transaction i think so this becomes a large change. So best to log it as discussion https://github.com/bitclout/cips and get buying from community & 1 core dev.

Thanks @tijno. Will post it under CIPs :)
