### ISSUE TITLE
Stop supporting TLS 1.0 and TLS 1.1

### ISSUE THREAD

**Issue by AlanDalton** [bitclout/frontend#271]
The server seems to support TLS 1.0 and TLS 1.1: https://www.ssllabs.com/ssltest/analyze.html?d=bitclout.com&s=104.18.24.35 …but this seems, to me, to present security issues: https://blog.qualys.com/product-tech/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols

**Comment by maebeam** [comment]
Done, thanks!
