### ISSUE TITLE
Set the X-Frame-Options header to “SAMEORIGIN” to prevent clickjacking attacks

### ISSUE THREAD

**Issue by AlanDalton** [bitclout/frontend#272]
Setting the site’s “X-Frame-Options” header to “SAMEORIGIN” would tell browsers to not allow the site to be framed. That should help prevent clickjacking attacks. See https://scotthelme.co.uk/hardening-your-http-response-headers/#x-frame-options

**Comment by maebeam** [comment]
We set `frame-ancestor 'self'` in the CSP which accomplishes the same thing.
