### ISSUE TITLE
Account switcher change broke on iOS

### ISSUE THREAD

**Issue by tijno** [bitclout/frontend#281]
iOS 14.6
Safari

See the issue below.

Tapping an account in new selector on iOS closes selector window and triggers link below it.

![image](https://user-images.githubusercontent.com/69529928/125511299-929cbe14-4063-4232-a71c-b72f944cd5e3.gif)

**Comment by AdityaChaudhary0005** [comment]
this is not just with iOS
same for me on chrome, Android.

seens like the dropdown works with mouse click only and not with touches

**Comment by maebeam** [comment]
Fixed here, thanks https://github.com/bitclout/frontend/pull/283
