### ISSUE TITLE
Soundcloud embedding issue

### ISSUE THREAD

**Issue by UnknownNFT** [bitclout/frontend#288]
Hi everyone! 

I hope this issue is in the right place.

Today I noticed SoundCloud embeds being much taller as they were before. I will show an example here.

Before:
![image](https://user-images.githubusercontent.com/83103574/125544350-967d66de-899c-414c-b8ec-37622aaac50e.png)

Now:
![image](https://user-images.githubusercontent.com/83103574/125544363-d36e1a1e-0d39-459b-97e3-9a463754e64a.png)

Both (comparison):
![image](https://user-images.githubusercontent.com/83103574/125544386-a81f8fdb-be45-447d-86c6-49b6a1013110.png)

As you can see, SoundCloud embeds are now much taller, and a lot more awkward and less visually appealing as before. :)

Please let me know if you need anything else!

**Comment by AdityaChaudhary0005** [comment]
seems like some padding issues..tbh i never tried soundCloud embeds yet..

**Comment by UnknownNFT** [comment]
> seems like some padding issues..tbh i never tried soundCloud embeds yet..

Ahh yes "padding" is the term I was looking for. I would imagine that could be the problem?

**Comment by UnknownNFT** [comment]
Update:

I just posted a soundcloud link today, and it seems the padding problem is resolved!
![image](https://user-images.githubusercontent.com/83103574/125646286-01c9ed5d-4cdf-49a3-8c68-e0f8c8c45ba0.png)

**Comment by UnknownNFT** [comment]
Hi everyone!!

Unfortunately, it seems this issue has popped back up, not sure if anyone else is experiencing this same problem of the Soundcloud padding expanding like crazy?

![image](https://user-images.githubusercontent.com/83103574/126263150-1a30d2c6-06a2-4074-a5a8-6791077780a7.png)

**Comment by UnknownNFT** [comment]
Small update, I did have the BitClout Plus extension installed from @iPaulPro.

After removing the extension and refreshing, it seems the padding issue goes away? Does anyone else share a similar experience as me? 

![image](https://user-images.githubusercontent.com/83103574/126429033-a66f2b13-f08d-4e69-857f-6ceaeeabfcef.png)

**Comment by iPaulPro** [comment]
> Small update, I did have the BitClout Plus extension installed from @iPaulPro.
> 
> After removing the extension, refreshing, and posting again, it seems the padding issue goes away? Does anyone else share a similar experience as me? 

Hm, this is curious since Plus doesn't touch those embeds. I'll look into it.

**Comment by iPaulPro** [comment]
Frontend client does some processing with the embed URLs that I assumed would happen on the server, so that's why this happens. This issue should be closed, since it's an issue only with BitClout+. Created [an issue](https://github.com/iPaulPro/BitCloutPlus/issues/5) for it in the plus repo.

**Comment by UnknownNFT** [comment]
> Frontend client does some processing with the embed URLs that I assumed would happen on the server, so that's why this happens. This issue should be closed, since it's an issue only with BitClout+. Created [an issue](https://github.com/iPaulPro/BitCloutPlus/issues/5) for it in the plus repo.

Ahh gotcha, no problem at all thank you very much for responding so quickly! Glad you were able to forward my issue to the correct place. :) 

I'll go ahead and close this thread! Thanks!
