### ISSUE TITLE
I am redirecting tabs continue when switch accounts

### ISSUE THREAD

**Issue by harpreet9629** [bitclout/frontend#289]
First of all, Thank You @lazynina  and team Now Account Switcher working fine.

https://github.com/bitclout/frontend/pull/244

I think This PR making issue when I switch accounts, it continues redirecting tabs on the same page.

https://bitclout.com/browse?feedTab=Following to https://bitclout.com/browse?feedTab=Global
and Global tab to Following

Please look at this, it freezes the whole page and can't able to do any action.

@maebeam  @cat-ico

**Comment by cat-ico** [comment]
@harpreet9629 Yes, you're right! Looking at it now.

**Comment by cat-ico** [comment]
@harpreet9629 I could only reproduce it once. After refreshing the page I can't reproduce it anymore. 
But this should fix it #291
