### ISSUE TITLE
Click on external links opens posts

### ISSUE THREAD

**Issue by jagathks** [bitclout/frontend#299]
Is there any specific reason for this functionality?
Clicking on external links in FeedPost opens up both the external urls (in new tab) and navigates to post page (in same tab).
Why do we have to navigate to post page when someone's intention is to view the external page/url only?
If users are interested in viewing post, the can click elsewhere on the feed/post!

Simple change is to remove -> `[routerLink]="['/' + globalVars.RouteNames.POSTS, postContent.PostHashHex]"`
If required i can submit a PR.

**Comment by tijno** [comment]
This was mentioned as a bug to be solved by one of the core devs. Just cant remember where 🤷‍♀️

**Comment by maebeam** [comment]
I'm not sure that change will solve this issue but please go ahead and fix it if you are able!
