### ISSUE TITLE
Strange notifications I'm not tagged in.

### ISSUE THREAD

**Issue by teambrixmusic** [bitclout/frontend#303]
Strange duplicate post in notifications that I was not tagged in at all.

![strange](https://user-images.githubusercontent.com/82254764/126075588-e6cd1c41-e1d1-4fab-a6e4-3b8d4db2118f.jpg)

**Comment by AdityaChaudhary0005** [comment]
i know how they did it. they had first tagged you and then they edited the post and removed the tag from post.
@teambrixmusic once i had made a post about it how you can enter someone's notification without tagging them

**Comment by teambrixmusic** [comment]
Okay yes they used cloutfeed to do this. I'll close this.
