### ISSUE TITLE
Reply box too small

### ISSUE THREAD

**Issue by KyleJSh** [bitclout/frontend#304]
Device: MacBook
Browser: Firefox
Node: bitclout.com, tijn.club
Issue: When replying to a post, the text field is too small.

<hr>

I disabled all my ad blockers and have already removed a bunch of plugins I wasn't using, for security reasons.

No change.

Seems to be fine on Chrome and Brave. Only Firefox is the problem.

Cheers!

![image](https://user-images.githubusercontent.com/30233330/126077378-3ee7935e-09e7-445c-a56f-3b441ec8c73d.png)

**Comment by harpreet9629** [comment]
It's fixed.

**Comment by KyleJSh** [comment]
Yup, looks good. Thanks!
