### ISSUE TITLE
Green Theme - white text hard to read

### ISSUE THREAD

**Issue by KyleJSh** [bitclout/frontend#305]
In green theme (on Chrome and Brave), it's difficult reading the white text against background R 188 G 238 B 250

Also, the mouseover on a post makes it difficult to read.

It seems fine on Firefox, but Chrome/Brave it's a problem.

![image](https://user-images.githubusercontent.com/30233330/126077607-377c1678-16fa-422e-9ef0-b3f780753be8.png)

**Comment by harpreet9629** [comment]
Checking This. 
Thanks

**Comment by maebeam** [comment]
Thanks for reporting
