### ISSUE TITLE
CloutVista link broken on searches that dont have a username

### ISSUE THREAD

**Issue by tijno** [bitclout/frontend#306]
@daniel-keyes 

looks like the link to clout vista disappears on longer searches - i think when no username match i found.

![20210718-uEuwZix3](https://user-images.githubusercontent.com/69529928/126082508-0a2a7e5a-a59a-49dd-bfa9-3030235304c0.gif)

**Comment by daniel-keyes** [comment]
Thanks for flagging this @tijno! I'll have a PR ready to fix it today.

Another issue I noticed, is that the cloutavista option pops up for the "Messages "and "Send Clout" search boxes as well. 
<img width="654" alt="Screen Shot 2021-07-19 at 14 53 01" src="https://user-images.githubusercontent.com/87264202/126156017-580472aa-b6a3-408d-972b-e54b2c4401ce.png">

This doesn't seem appropriate to the desired user behavior. I'll go ahead and fix that as well.
