### ISSUE TITLE
Theme Switcher can't add Class in Modal's

### ISSUE THREAD

**Issue by harpreet9629** [bitclout/frontend#310]
@lazynina  Here still an issue with this

https://github.com/JustifydWarrior/frontend/commit/32490d36c9d1327fd2f7ef8edbfb6b3188f1bce9#diff-a945c662b9f44ad5647af5e40a6738b08b16e7a9c2b5274c213a3a681a39e09f

It won't add class in modal's Please look at this.

**Comment by maebeam** [comment]
I believe this is fixed
