### ISSUE TITLE
Creator Coin Transfer Value NaN

### ISSUE THREAD

**Issue by HPaulson** [bitclout/frontend#32]
While making a Creator Coin Transfer, `creatorCoinTrade.amount.value` has a value of NaN on the transfer preview, even after an amount of creator coin to transfer is inputted. This occurs on both the form and preview.

https://github.com/bitclout/frontend/blob/e5e72fc4e8788ddc835510ccad4be707062b502f/src/app/trade-creator-page/trade-creator-table/trade-creator-table.component.html#L19

Form:
 ![image](https://user-images.githubusercontent.com/47159695/117225791-28483600-ade1-11eb-9109-de3f210c174b.png)

Preview:
![image](https://user-images.githubusercontent.com/47159695/117225782-24b4af00-ade1-11eb-9073-2847b6920394.png)

**Comment by maebeam** [comment]
Can you provide reproduction steps?

**Comment by lazynina** [comment]
@HPaulson Is this still an issue? Can you show us how to reproduce? If not, would like to close this issue.

**Comment by HPaulson** [comment]
@lazynina Very sorry! Will check to see if it's still occurring.

**Comment by maebeam** [comment]
Gonna close this unless you're able to reproduce. Thanks!
