### ISSUE TITLE
"Message" Button in Profile Page

### ISSUE THREAD

**Issue by simoncharlie** [bitclout/frontend#323]
![Capture](https://user-images.githubusercontent.com/87218742/127020690-acb045bb-a815-45d0-90f1-4fec34d901a2.PNG)
As a user, we need a MESSAGE button near the Unfollow & Buy buttons when we're in someone's profile so we can hit message easily  rather than go to Messages sidetab and copy-paste the name

**Comment by maebeam** [comment]
Great idea, pull requests are welcomed

**Comment by harpreet9629** [comment]
Its Solved by @lazynina he added in dropdown :)

**Comment by simoncharlie** [comment]
nice
