### ISSUE TITLE
Issue on Loading Messages

### ISSUE THREAD

**Issue by harpreet9629** [bitclout/frontend#335]
There's issue on Loading Messages, it show blank box

![image](https://user-images.githubusercontent.com/26606638/127389720-d0053db8-cedd-4217-81d5-70dc20822015.png)

**Comment by teambrixmusic** [comment]
That's what's happenning to me too whenever I send from cloutfeed

**Comment by maebeam** [comment]
I'm unable to reproduce. Are there any errors in the console?

**Comment by harpreet9629** [comment]
Its now fixed. May be that time node or blockchain is slow :)

I am closing this issue.
