### ISSUE TITLE
NFT owner showing as actor in notifications for bids

### ISSUE THREAD

**Issue by tijno** [bitclout/frontend#336]
![20210728-hHJYVS1B](https://user-images.githubusercontent.com/69529928/127401336-dbcb65e3-0f05-4d67-8264-7144b72875aa.png)

https://github.com/bitclout/frontend/blob/cf55ceed04682ac5801bfcf38324bc1e489d7fd6/src/app/notifications-page/notifications-list/notifications-list.component.ts#L271

Unclear what is causing this on first glance as its getting the TransactorPubKey to define the actor. Which suggests there may be an issue in backend ?

**Comment by lazynina** [comment]
this should be resolved with the below PRs - just had the usernames flopped by accident
https://github.com/bitclout/frontend/pull/340
https://github.com/bitclout/frontend/pull/338

**Comment by tijno** [comment]
thx
