### ISSUE TITLE
NFT Minting Pop-up - Grammatical error

### ISSUE THREAD

**Issue by AikonMishima** [bitclout/frontend#343]
Although this isn't a large issue, there's a typo / grammatical error in the "Royalties" section of the NFT Settings pop-up.

The word "the" should be removed in this sentence.

<img width="780" alt="Schermafbeelding 2021-07-29 om 15 55 12" src="https://user-images.githubusercontent.com/84419699/127505002-b320f382-8603-4236-a5d9-43eaf9fd5f4e.png">

**Comment by fungibles** [comment]
You could also change the "close auctions" by dropping the s since its just one auction

**Comment by tijno** [comment]
@fungibles i think closing auctions is probably ok as it relates to NFTs that have multiple serials and therefore when closing the NFT you would close multiple auctions.
