### ISSUE TITLE
Error when trying to delete an NFT post

### ISSUE THREAD

**Issue by fungibles** [bitclout/frontend#345]
<img width="471" alt="Screen Shot 2021-07-29 at 10 40 37 PM" src="https://user-images.githubusercontent.com/87679340/127606369-15806309-543f-471f-84d0-15b919210fcb.png">

Received this error after I minted an NFT and then tried to delete it before closing the auction. I also received this error when trying to hide my NFT post after I closed the auction. I wanted to hide this because of an issue with arweave that I will post in another ticket

**Comment by tijno** [comment]
I think this is intentional @fungibles - ones minted - it can not be changed or hidden as its a NFT. Only option is to make sure the auction is closed so it can not be sold.

**Comment by lazynina** [comment]
@tijno is correct. Once a post is minted as an NFT, it is not possible to change the contents of or hide the post. A user could manipulate a post after selling it as an NFT thus changing the value of it (potentially decreasing it significantly). If you have further concerns regarding this issue, please re-open if you have further concerns on this issue

**Comment by fungibles** [comment]
Thanks!
