### ISSUE TITLE
This Post is NOT an NFT "Typo" lol

### ISSUE THREAD

**Issue by teambrixmusic** [bitclout/frontend#349]
![dddddd](https://user-images.githubusercontent.com/82254764/127730949-8f3c0fe6-4930-41fe-b20a-72a55b05f95f.jpg)

Thought this was funny when I saw it and people have been minting these lol.

But it's a legit typo. Lol

**Comment by AdityaChaudhary0005** [comment]
i am not able to see the typo here lol help me see it

**Comment by maebeam** [comment]
What's the typo?

**Comment by chrismaddern** [comment]
This is the confirmation dialog after making an NFT.

I presume it should be
> This post is no**w** an NFT

**Comment by tijno** [comment]
Its not a typo - the dialog should not show.

I think it shows because visitor is redirected to nft url too soon - eg before its known as a nft

https://github.com/bitclout/frontend/blob/63bb6f0cd811e664705042a7841d830dc653dc16/src/app/nft-post-page/nft-post/nft-post.component.ts#L111

**Comment by lazynina** [comment]
this should be resolved with #378

**Comment by maebeam** [comment]
Closing since #378 was merged
