### ISSUE TITLE
Not showing NFT sale on profile

### ISSUE THREAD

**Issue by electro89** [bitclout/frontend#352]
If I make a mint a nft with put in on sale off , and make it on sale later , it won't show on profile page nft sale section.

**Comment by electro89** [comment]
It happened with multiple NFT option

**Comment by lazynina** [comment]
@electro89 are you still experiencing this issue? I believe we have resolved it - we needed to rebuild some indexes. Please let me know if you're still experiencing this issue or if we can close this issue.

**Comment by maebeam** [comment]
Please reopen if this issue is still valid. Thanks!
