### ISSUE TITLE
Reselling NFT not showing on profile

### ISSUE THREAD

**Issue by electro89** [bitclout/frontend#353]
If I resell NFT bought, it is not showing on sale section.

**Comment by electro89** [comment]
Happened with multiple NFTs option

**Comment by ShhubhamA** [comment]
happened with me  too! I guess there is some bug

**Comment by lazynina** [comment]
@electro89 is this still happening? I think we put in a fix to resolve this issue?

**Comment by maebeam** [comment]
Please reopen if this issue is still valid. Thanks!
