### ISSUE TITLE
Ardrive image not showing in post

### ISSUE THREAD

**Issue by AdityaChaudhary0005** [bitclout/frontend#367]
ArDrive image doesn't shows up when the post body contains any web page URL.

EDIT: by ArDrive i mean the usual arweave.net images

EDIT2: 

the post with no URL in body: https://bitclout.com/nft/73e3f969709cb50ca469dd42bf76c695eff6f6a30396b5c4b87920b7aa5d78e5?tab=posts (shows the arweave image)

the post with a URL in body: https://bitclout.com/posts/e41cd0855ba10359821adf589e24d93e32fe013d5ee0162e39b93e7d8942ab06 (doesn't show arweave image)

both posts contains same arweave image link

**Comment by dgsus** [comment]
so far only AR whitelisted domain was arweave.net not ardrive.io

**Comment by AdityaChaudhary0005** [comment]
yeah, i actually meant the usual arweave.net (my bad i wrote ardrive in original issue).

problem is image shows only when the post does not has any URL in body. if the body has URL, it doesn't shows the image.

**Comment by tijno** [comment]
do you have the single post stateless `body` response ?

**Comment by AdityaChaudhary0005** [comment]
@tijno check it here:

the post with no URL in body: https://bitclout.com/nft/73e3f969709cb50ca469dd42bf76c695eff6f6a30396b5c4b87920b7aa5d78e5?tab=posts (shows the arweave image)


the post with a URL in body: https://bitclout.com/posts/e41cd0855ba10359821adf589e24d93e32fe013d5ee0162e39b93e7d8942ab06 (doesn't show arweave image)

**Comment by tijno** [comment]
Looks like its not stored so it must go wrong at post time. 

![20210806-DHte0tSi](https://user-images.githubusercontent.com/69529928/128512739-8d765391-4d11-4f57-aa8a-e19149133374.png)

**Comment by tijno** [comment]
@AdityaChaudhary0005 

cant replicate

https://bitclout.com/posts/1066c7e33d3df8b96335614a2409c66e6433b16c3041e935237c7af7089d4799

transaction includes base64 of body & arweave url

`eyJCb2R5IjoidGhpcyBpcyBhIHRlc3RcblxudGlqbi5jbHViXG5cbiIsIkltYWdlVVJMcyI6WyJodHRwczovL2dvdzR2cXMyeDVhNGRheHdleWhranhmdDc0Zm5odmR0cHgyamk1ZWJka3djM2htY3ZrcHEuYXJ3ZWF2ZS5uZXQvTTYzS3dscV9RY0dDOWlZT3BOeXpfd3JUMUhOOTlKUjBnUnFzTFoyQ3FwOCJdfQ==`

![20210806-0DRI0spg](https://user-images.githubusercontent.com/69529928/128513387-13f33976-d5ce-407c-b35f-e1fcff9f1864.png)

**Comment by maebeam** [comment]
This is an issue with BitClout Plus. Maybe open an issue there: https://github.com/iPaulPro/BitCloutPlus
