### ISSUE TITLE
Twitter image card of https://bitclout.com is blank

### ISSUE THREAD

**Issue by carlosgnet** [bitclout/frontend#379]
When someone tweets a link to [bitclout.com](https://bitclout.com) the Twitter Card shows a blank image:

![image_2021-08-11_195930](https://user-images.githubusercontent.com/18427657/129079738-a0a505f4-6f2c-4381-9365-ec531e409840.png)

The [code of index.html seems OK](https://github.com/bitclout/frontend/blob/fa3ca88ab28d44777858828aa388b59b8b447f87/src/index.html#L10) and the linked image exists.

The [Twitter Card validator](https://cards-dev.twitter.com/validator) returns a success.

As per [this Twitter Forum thread](https://twittercommunity.com/t/card-error-unable-to-render-or-no-image-read-this-first/62736) the problem seems to be that the Twitter bot crawler can't access the image. And indeed, that is the case because [the image returns a 404](https://bitclout.com/assets/img/camelcase_logo_og.jpg).

I think maybe the problem is just a minor robots.txt misconfiguration or something related to the new antispam measures.

**Comment by maebeam** [comment]
Fixed in 6da628511f8994e7a587abd983cfcb58fecbc66d

Thanks!
