### ISSUE TITLE
Should post thread hide all replies by the users post creator blocked?

### ISSUE THREAD

**Issue by tijno** [bitclout/frontend#387]
This relates to the issue mentioned [here](https://bitclout.com/posts/cab9844e8b74c6cf1663df7e89c85fdce101e425fba10628968570e9efca1589)  and [here](https://bitclout.com/posts/c33eb3340d8f740f8c48aab5754744152741d86d18f8e395b693ba0eda39f75c)   by @AdityaChaudhary0005 and @FreeTrade

Replies by someone the post owner has blocked are hidden for everyone.

Not sure if this is intentional, or bug.

@maebeam if intentional ill raise cip to propose change.

This uses the post creator pub key - but should it not use the logged in user key ?

https://github.com/bitclout/frontend/blob/cbed73cc0378974597cfa8fef386df53b59bb170/src/app/post-thread-page/post-thread/post-thread.component.ts#L343

**Comment by AdityaChaudhary0005** [comment]
My take on this:

- Giving the poster the power to censor users in comments isn't a good thing at all for a "decentralised social media". This is not even the case with centralised platforms like Twitter

- In future, if politicians ever join BitClout, they can easily censor the voice of media and opposition party and users will think that the politician is good enough that no one opposes him.

- I understand, this prevents visibility of spam comments which is a good thing but to solve this issue we can simply hide the post and give a "Show hidden comment" button or something just like we have one on twitter.

Last but not the least, @maebeam knows it what it feels like being censored even when you are right. ![IMG_20210815_155138.png](https://user-images.githubusercontent.com/55331140/129475257-880982ce-5c91-49ea-b25e-141f298b5d3b.png)

**Comment by tijno** [comment]
@AdityaChaudhary0005 So its not a bug and its intentional? 

If it is intentional then this needs to be discussed as a CIP - hence me being keen to figure out if it is a bug or a "feature"

Note i agree with what you are saying by the way.

But fixing a bug will be much easier then changing this if it was intentional.

**Comment by AdityaChaudhary0005** [comment]
Yeah, to me it looks like it is intentional but we should wait for the response of core Devs 🙂

If it's intentional, we will CIP it and if it's a bug we can do a PR to fix it

**Comment by FreeTrade** [comment]
I'm assuming it's intentional - if so, perhaps there could be an option to switch it on/off depending on the node operator's preference.

**Comment by maebeam** [comment]
This is intentional. CIP is welcomed.

**Comment by tijno** [comment]
@AdityaChaudhary0005 @FreeTrade as you discovered the issue you want to raise the CIP? If not i can do it of course.

**Comment by FreeTrade** [comment]
No, I'm working on alternative software, so I won't to get too deeply involved with improvements to the BC frontend.
