### ISSUE TITLE
Stuck on tutorial (Step 2). Can't do anything

### ISSUE THREAD

**Issue by AdityaChaudhary0005** [bitclout/frontend#411]
The tutorial is frozen here and I can't do anything. It says to sell a CC but buttons do not works at all.
![Screenshot from 2021-08-24 19-13-08](https://user-images.githubusercontent.com/55331140/130627482-fb3b4dbe-2525-4d57-8e50-3f3fb583ff2d.png)

If I try go to URL `bitclout.com` it redirects me to `https://bitclout.com/tutorial/wallet/dharmesh` which is where coming out of this buggy loop is almost impossible unless I search a user in search bar and go to his page.
On a side note, according to the tutorial, I had already bought and sold $Dharmesh still the page expects me to sell coins.

A good solution would be to have a "Skip this step" or something

EDIT: Console shows these errors:
![Screenshot from 2021-08-24 19-24-30](https://user-images.githubusercontent.com/55331140/130629370-8bc20f37-3ceb-4a86-859a-890fd9e32142.png)

EDIT2: What is meant by "Sell a creator" ? Ain't this should be "Sell a creator coin" ?

**Comment by tijno** [comment]
There should be a next step button - I had trouble seeing it on mobile, but after a few minutes of trying to scroll the window it did show.

Also the tutorial has been removed so if you do a hard refresh - maybe you are ok now.

**Comment by AdityaChaudhary0005** [comment]
Closing this as it is fixed by Nina!
