### ISSUE TITLE
Following and Follower Lists Don't "Load More"

### ISSUE THREAD

**Issue by teambrixmusic** [bitclout/frontend#416]
On Bitclout.com node the following list and followers list don't show all the followers followees. They no longer "Load more" after the first page. No plugins activated. On latest chrome desktop windows 10 pro

**Comment by AdityaChaudhary0005** [comment]
yup, only few top followers load and at one point we can't scroll down anymore

**Comment by AdityaChaudhary0005** [comment]
It works after the notification scroll fixes @lazynina !
