### ISSUE TITLE
Founder reward helper text is showing on Creator Coin sale

### ISSUE THREAD

**Issue by chafreaky** [bitclout/frontend#43]
The helper text showing the percentage of the founding reward going to the creator is now also displaying when trying to sell a creator coin. This will cause confusion as people will believe founding rewards are paid on every transactions.

I think this was introduced in https://github.com/bitclout/frontend/commit/0fbce8f3a39cdecfdc5c83011814f0634264649c @redpartyhat @lazynina 

See screenshot.

<img width="601" alt="Screenshot 2021-05-07 at 09 40 22" src="https://user-images.githubusercontent.com/4400527/117423262-701da900-af18-11eb-98f6-a280abe4c379.png">

**Comment by maebeam** [comment]
Fixed by #48, thanks!
