### ISSUE TITLE
[Suggest] Show user's info when pasted the public key to transfer coin

### ISSUE THREAD

**Issue by tamdc2704** [bitclout/frontend#44]
I think this feature will help user feel safe when make a transaction
![image](https://user-images.githubusercontent.com/20236099/117457247-3e85fb80-af73-11eb-9520-78b001f554cf.png)

**Comment by phaitonican** [comment]
Maybe use the amounts of money to male a viable platform fucking fat class b fake profil programmer. What about hashtags you big big dumbfuck

**Comment by phaitonican** [comment]
Be ashamed piece of shit maebaem fat idiot

**Comment by phaitonican** [comment]
All u programmed is a feed on blockchain not even supporting hashtags what a shit

**Comment by phaitonican** [comment]
Be ashamed man you will be lonely ur entkre life

**Comment by jagathks** [comment]
Isn't this already done.
![image](https://user-images.githubusercontent.com/17216156/125476709-2974e430-19d9-44f4-9859-6a1bba4bb799.png)

**Comment by maebeam** [comment]
This is done, thanks everyone
