### ISSUE TITLE
ETH deposit address changed, funds gone

### ISSUE THREAD

**Issue by tijno** [bitclout/frontend#449]
@maebeam looks like my ETH deposit address changed from the one i deposited some test funds to, and now funds are gone.

Steps:

1. No deposit address shown, re authenticated account with identity

2. Copied provided address:
0xa0D5DF4024e0DBE01B56E0872c003Db2c328BeeB

3. Deposit $10 funds TxId: 50a1be20-7729-4201-8287-27adc4830df1

4. Tried buy clout but transaction kept failing - presumed i needed to wait for a bit

5. Still failing earlier so i see authenticated my account with identity

6. Deposit address changed with 0 balance to: 0x2b9712B2FDd5627eaDDB803C5524bAcd616A2C53

**Comment by maebeam** [comment]
Unfortunately there was ~10 minutes where an incorrect ETH deposit address was visible. We will send you some $CLOUT to cover the lost funds.
