### ISSUE TITLE
Getting Incorrect Value for nanosToUSD and nanosToUSDNumber

### ISSUE THREAD

**Issue by AdonousTech** [bitclout/frontend#71]
I'm running some tests using a couple of the conversion methods from the globalvars service in the app. Specifically:

`    nanosToUSDNumber(nanos: number): number {
        const result = nanos / this.nanosPerUSDExchangeRate;
        console.log('[RESULT] ::  ', result);
        return result;
    }
    
    nanosToUSD(nanos: number, decimal?: number): string {
        if (decimal == null) {
            decimal = 4;
        }

        const result: string = this.formatUSD(this.nanosToUSDNumber(nanos), decimal);
        console.log('[RESULT] :: ', result);
        return result;
    }`

I did a real-time pull of the required nanos value from the get-single-profile API call. I even verified the BitClout frontend at bitclout.com is fetching the same values.

When using the following value and running it through the function, its completely off.

Test Value:  1090670098 (Profile.CoinPriceBitCloutNanos) should represent a coin price of ~$190 (according to the BitClout frontend). 

I have passed the test value to both methods above, exactly as shown in the frontend code here:

` ~{{ globalVars.nanosToUSD(profile.CoinPriceBitCloutNanos, 2) }}`

https://github.com/bitclout/frontend/blob/a752edf2ec9f3003664cbfb4192cccac5b0a8816/src/app/creator-profile-page/creator-profile-top-card/creator-profile-top-card.component.html#L109

When I run the calculation, I get $1.0907, which is clearly incorrect.

I even put together several permutations, and no luck. You can quickly test out my exact code in this StackBlitz project:

https://stackblitz.com/edit/angular-ivy-5nq93r?devtoolsheight=33&file=src/app/app.component.ts

All other nano conversions I have tried work properly (coins in circulation, timestamp, nano to bitclout).

Am I missing something??

**Comment by AdonousTech** [comment]
My bad. You can close this. I realized I was not using the appropriate formula. I thought it was being calculated in the frontend.

**Comment by xihadandan** [comment]
Encounter the same problem
