### ISSUE TITLE
Implement Hashtags

### ISSUE THREAD

**Issue by phaitonican** [bitclout/frontend#88]
I don't know programming Typescript etc, but will there be hashtags soon?

**Comment by maebeam** [comment]
You're welcome to fork the repos and build them yourself

**Comment by phaitonican** [comment]
I told you i cant. Fucking idiots release a platform not even has hashtags what have u done with all the money be ashamed

**Comment by phaitonican** [comment]
Fucking fake profil maebaem some fat class b programmer
